[workspace]
members = [
    "github/slack/star-messager",
    "github/slack/issue-notifier",
    "github/gmail/star-thanks-by-gmail",
    "github/sendgrid/star-thanks-by-sendgrid",
    "slack/slack/calculator"
]
