[package]
name = "issue-pr-naive-bot"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/issue-pr-naive-bot.rs"
crate-type = ["cdylib"]

[dependencies]
flows-connector-dsi = { version = "0.1.0" }
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"
