[package]
name = "branch-tag-created"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/branch-tag-created.rs"
crate-type = ["cdylib"]

[dependencies]
flows-connector-dsi = { version = "0.1.0" }
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"
